USE db_cursores

CREATE TABLE TB_FUNCIONARIO (
  MATRICULA INT NOT NULL PRIMARY KEY,
  NOME VARCHAR(50) NOT NULL
) 

CREATE TABLE TB_DEPENDENTES (
  ID_DEPENDENTE INT NOT NULL IDENTITY(1,1),
  MATRICULA INT NOT NULL REFERENCES TB_FUNCIONARIO(MATRICULA),
  NOME VARCHAR(50) NOT NULL
  PRIMARY KEY (ID_DEPENDENTE, MATRICULA)
)

INSERT INTO TB_FUNCIONARIO VALUES (1, 'JOSÉ RICARDO')
INSERT INTO TB_FUNCIONARIO VALUES (2, 'ANA MILLER')

INSERT INTO TB_DEPENDENTES VALUES (1, 'ROBERTA'),
                                  (1, 'RITA'),
				  (1, 'GABRIELA')

INSERT INTO TB_DEPENDENTES VALUES (2, 'GUSTAVO'),
                                   (2, 'MARIANA')

DECLARE @MATRICULA INT, @NOME VARCHAR(50), @NOME_DEPENDENTE VARCHAR(50)
DECLARE C_FUNC CURSOR FOR SELECT F.MATRICULA, F.NOME FROM TB_FUNCIONARIO F INNER JOIN TB_DEPENDENTES D ON (F.MATRICULA = D.MATRICULA)
DECLARE C_DEP CURSOR FOR SELECT D.NOME FROM TB_FUNCIONARIO F INNER JOIN TB_DEPENDENTES D ON (F.MATRICULA = D.MATRICULA)
OPEN C_FUNC
OPEN C_DEP
FETCH C_FUNC INTO @MATRICULA, @NOME
FETCH C_DEP INTO @NOME_DEPENDENTE
while(@@FETCH_STATUS = 0)
	BEGIN
		PRINT TRIM(STR(@MATRICULA)) + ' ' + @NOME
			WHILE(@@FETCH_STATUS = 0)
			BEGIN
				PRINT ' ' + @NOME_DEPENDENTE
				FETCH C_DEP INTO @NOME_DEPENDENTE
			END
		FETCH C_FUNC INTO @MATRICULA, @NOME
	END
CLOSE C_FUNC
DEALLOCATE C_FUNC
CLOSE C_DEP
DEALLOCATE C_DEP
