CREATE DATABASE db_cursores

USE db_cursores

CREATE TABLE TB_ALUNO (
	matricula int not null primary key,
	nome varchar(50) not null,
	dt_nascimento datetime not null
)

INSERT INTO TB_ALUNO
	VALUES(1, 'JOAO', '19760812'),
		  (2, 'RICARDO', '19700123'),
		  (3, 'ROBERTO', '19890726')

DECLARE @MAT INT
DECLARE @NOME_ALUNO VARCHAR(50)
DECLARE @DATA DATETIME

DECLARE C_ALUNOS CURSOR FOR SELECT * FROM TB_ALUNO
OPEN C_ALUNOS
FETCH C_ALUNOS INTO @MAT, @NOME_ALUNO, @DATA
while(@@FETCH_STATUS = 0)
	BEGIN
		PRINT TRIM(STR(@MAT)) + ' ' + @NOME_ALUNO + ' ' + CONVERT(VARCHAR(12), @DATA)
		FETCH C_ALUNOS INTO @MAT, @NOME_ALUNO, @DATA
	END
CLOSE C_ALUNOS
DEALLOCATE C_ALUNOS