CREATE DATABASE bdII_visoes02

USE bdII_visoes02

DROP TABLE TB_VENDAS_S02_2021
DROP TABLE TB_VENDAS_S01_2022
DROP TABLE TB_VENDAS_S02_2022

CREATE TABLE TB_VENDAS_S02_2021(
	CD_PRODUTO INT NOT NULL,
	CD_FUNCIONARIO INT NOT NULL,
	DT_VENDA DATETIME NOT NULL CHECK (DT_VENDA >= '20210701' AND DT_VENDA < '20220101'),
	VALOR_VENDA NUMERIC(10,2) NOT NULL
	PRIMARY KEY(CD_PRODUTO, CD_FUNCIONARIO, DT_VENDA)
)

CREATE TABLE TB_VENDAS_S01_2022(
	CD_PRODUTO INT NOT NULL,
	CD_FUNCIONARIO INT NOT NULL,
	DT_VENDA DATETIME NOT NULL CHECK (DT_VENDA >= '20220101' AND DT_VENDA < '20220701'),
	VALOR_VENDA NUMERIC(10,2) NOT NULL
	PRIMARY KEY(CD_PRODUTO, CD_FUNCIONARIO, DT_VENDA)
)

CREATE TABLE TB_VENDAS_S02_2022(
	CD_PRODUTO INT NOT NULL,
	CD_FUNCIONARIO INT NOT NULL,
	DT_VENDA DATETIME NOT NULL CHECK (DT_VENDA >= '20220701' AND DT_VENDA < '20230101'),
	VALOR_VENDA NUMERIC(10,2) NOT NULL
	PRIMARY KEY(CD_PRODUTO, CD_FUNCIONARIO, DT_VENDA)
)

CREATE VIEW VW_VENDAS AS
SELECT * FROM TB_VENDAS_S01_2022
UNION ALL
SELECT * FROM TB_VENDAS_S02_2021
UNION ALL
SELECT * FROM TB_VENDAS_S02_2022

INSERT INTO VW_VENDAS
VALUES(2,2,'20220722',22.30)

UPDATE VW_VENDAS
SET DT_VENDA = '20220723'
WHERE CD_PRODUTO = 1


CREATE TABLE TB_FUNCIONARIO_SE(
	MATRICULA INT NOT NULL,
	NM_FUNCIONARIO VARCHAR(40) NOT NULL,
	ESTADO CHAR(2) NOT NULL CHECK (ESTADO = 'SE'),
	SALARIO NUMERIC (10,2)
	PRIMARY KEY(MATRICULA, ESTADO)
)

CREATE TABLE TB_FUNCIONARIO_PB(
	MATRICULA INT NOT NULL,
	NM_FUNCIONARIO VARCHAR(40) NOT NULL,
	ESTADO CHAR(2) NOT NULL CHECK (ESTADO = 'PB'),
	SALARIO NUMERIC (10,2)
	PRIMARY KEY(MATRICULA, ESTADO)
)

CREATE TABLE TB_FUNCIONARIO_AL(
	MATRICULA INT NOT NULL,
	NM_FUNCIONARIO VARCHAR(40) NOT NULL,
	ESTADO CHAR(2) NOT NULL CHECK (ESTADO = 'AL'),
	SALARIO NUMERIC (10,2)
	PRIMARY KEY(MATRICULA, ESTADO)
)

CREATE VIEW VW_FUNCIONARIO AS
SELECT * FROM TB_FUNCIONARIO_SE
UNION ALL
SELECT * FROM TB_FUNCIONARIO_PB
UNION ALL
SELECT * FROM TB_FUNCIONARIO_AL

INSERT INTO VW_FUNCIONARIO
	VALUES(2,'Alberto','PB',22.30),
		  (3,'Sergio','AL',22.30)

UPDATE VW_FUNCIONARIO
SET ESTADO = 'PB'
WHERE MATRICULA = 1

