
-- EX 01
CREATE TABLE TB_FORNECEDOR(
    CD_FORNECEDOR NUMBER PRIMARY KEY,
    NM_FORNECEDOR VARCHAR2(50),
    NM_CONTATO VARCHAR(30),
    DT_CADASTRO DATE DEFAULT(SYSDATE)
)

CREATE SEQUENCE SQ_FORNECEDOR 
START WITH 1
INCREMENT BY 1

INSERT INTO TB_FORNECEDOR(CD_FORNECEDOR, NM_FORNECEDOR,
                        NM_CONTATO)
                        VALUES(SQ_FORNECEDOR.NEXTVAL,
                                'TEK-PIX',
                                '0800 777 7000')


-- EX 02
CREATE OR REPLACE PROCEDURE SP_INCLUI_FORNECEDOR
(NM_FORNECEDOR IN VARCHAR2, 
NM_CONTATO IN VARCHAR2,
CD_FORNECEDOR OUT NUMBER)
AS
BEGIN
    
    INSERT INTO TB_FORNECEDOR(CD_FORNECEDOR, NM_FORNECEDOR,
                             NM_CONTATO)
                            VALUES(SQ_FORNECEDOR.NEXTVAL,
                                    NM_FORNECEDOR,
                                    NM_CONTATO);
    CD_FORNECEDOR := SQ_FORNECEDOR.CURRVAL;
    
END;

DECLARE
    CD_FORNECEDOR NUMBER;
BEGIN
    SP_INCLUI_FORNECEDOR('FANTA','555-444-333',CD_FORNECEDOR);
    DBMS_OUTPUT.PUT_LINE(CD_FORNECEDOR);
END;

