CREATE OR REPLACE PROCEDURE SP_IMPOSTO_RENDA (RENDA IN NUMBER,
IMPOSTO OUT NUMBER)
AS
BEGIN
    IMPOSTO := 0;
    IF RENDA >= 1372.82 AND RENDA <= 2743.25 THEN
        IMPOSTO := (RENDA * 0.15) + 205.92;
    END IF;
    IF RENDA > 2743.25 THEN
        IMPOSTO := (RENDA * 0.275) + 548.82;
    END IF;
END;

CREATE TABLE TB_FUNCIONARIO(
    ID NUMBER PRIMARY KEY,
    NM_FUNCIONARIO VARCHAR2(50) NOT NULL,
    SALARO NUMBER(10,2) NOT NULL,
    IMPOSTO NUMBER(10,2)
);

DECLARE 
    CURSOR C_FUNCIONARIO IS SELECT * FROM TB_FUNCIONARIO;
    R_FUNCIONARIO C_FUNCIONARIO%ROWTYPE;
    IMPOSTO_RENDA NUMERIC(10,2);
BEGIN
    OPEN C_FUNCIONARIO;
    FETCH C_FUNCIONARIO INTO R_FUNCIONARIO;
    WHILE C_FUNCIONARIO%FOUND LOOP
        SP_IMPOSTO_RENDA(R_FUNCIONARIO.SALARO,IMPOSTO_RENDA);
        UPDATE TB_FUNCIONARIO SET IMPOSTO = IMPOSTO_RENDA
        WHERE ID = R_FUNCIONARIO.ID;
        FETCH C_FUNCIONARIO INTO R_FUNCIONARIO;
    END LOOP;
    CLOSE C_FUNCIONARIO;
END;

INSERT INTO TB_FUNCIONARIO
VALUES(1,'Moises',100, 0);

INSERT INTO TB_FUNCIONARIO
VALUES(2,'Garelax',2000, 0);

INSERT INTO TB_FUNCIONARIO
VALUES(3,'Garelax',1500, 0);

SELECT * FROM TB_FUNCIONARIO;
