CREATE OR REPLACE PROCEDURE SP_AUMENTO_SALARIO
(ANO IN INT, SALARIO_ATUAL IN NUMBER, AUMENTO OUT NUMBER)
AS
BEGIN
    IF ANO < 2000 THEN
        AUMENTO := (SALARIO_ATUAL * 0.2);
    END IF;
    IF ANO >= 2000 AND ANO <= 2004 THEN
        AUMENTO := (SALARIO_ATUAL * 0.1);
    END IF;
    IF ANO >= 2005 THEN
        AUMENTO := (SALARIO_ATUAL * 0.05);
    END IF;
END;


CREATE TABLE TB_FUNCIONARIO (
    MATRICULA INT NOT NULL,
    NM_FUNCIONARIO VARCHAR2(50) NOT NULL,
    ANO_ADMISSAO INT NOT NULL,
    SALARIO NUMBER(10,2) NOT NULL
);

INSERT INTO TB_FUNCIONARIO 
VALUES (1,'T',1998,100);
INSERT INTO TB_FUNCIONARIO 
VALUES (2,'T',2000,100);
INSERT INTO TB_FUNCIONARIO 
VALUES (3,'T',2005,100);
SELECT * FROM TB_FUNCIONARIO;

/*CREATE OR REPLACE PROCEDURE SP_ATUALIZA_SALARIO
AS
BEGIN
    DECLARE CURSOR C_FUNCIONARIO IS SELECT * FROM TB_FUNCIONARIO;
    DECLARE R_FUNCIONARIO := C_FUNCIONARIO%ROWTYPE;
    DECLARE AUMENTO NUMBER(10,2);
    OPEN C_FUNCIONARIO;
    FETCH C_FUNCIONARIO INTO R_FUNCIONARIO;
    WHILE C_FUNCIONARIO%FOUND LOOP
        SP_AUMENTO_SALARIO (R_FUNCIONARIO.ANO_ADMISSAO,
                            R_FUNCIONARIO.SALARIO,
                            AUMENTO);
        UPDATE TB_FUNCIONARIO SET SALARIO = (SALARIO + AUMENTO)
        WHERE MATRICULA = R_FUNCIONARIO.MATRICULA;
        FETCH C_FUNCIONARIO INTO R_FUNCIONARIO;
    END LOOP;
    CLOSE C_FUNCIONARIO;
END;*/

DECLARE 
    CURSOR C_FUNCIONARIO IS SELECT * FROM TB_FUNCIONARIO;
    R_FUNCIONARIO C_FUNCIONARIO%ROWTYPE;
    AUMENTO NUMERIC(10,2);
BEGIN
    OPEN C_FUNCIONARIO;
    FETCH C_FUNCIONARIO INTO R_FUNCIONARIO;
    WHILE C_FUNCIONARIO%FOUND LOOP
        SP_AUMENTO_SALARIO (R_FUNCIONARIO.ANO_ADMISSAO,
                            R_FUNCIONARIO.SALARIO,
                            AUMENTO);
        UPDATE TB_FUNCIONARIO SET SALARIO = (SALARIO + AUMENTO)
        WHERE MATRICULA = R_FUNCIONARIO.MATRICULA;
        FETCH C_FUNCIONARIO INTO R_FUNCIONARIO;
    END LOOP;
    CLOSE C_FUNCIONARIO;
END;