CREATE DATABASE ex_11

use ex_11

CREATE TABLE TB_USUARIO (
  CD_USUARIO INT NOT NULL PRIMARY KEY,
  NM_USUARIO VARCHAR(60) NOT NULL,
  CPF INT NULL
)

CREATE TABLE TB_LANCAMENTOS (
   CD_LANCAMENTO INT NOT NULL PRIMARY KEY IDENTITY(1,1),
   MES INT NOT NULL,
   ANO INT NOT NULL,
   CD_USUARIO INT NOT NULL,
   TP_LANCAMENTO VARCHAR(1) CHECK (TP_LANCAMENTO IN ('R', 'D')),
   DESCRICAO VARCHAR(200) NOT NULL,
   VALOR NUMERIC(10,2) NOT NULL
)


CREATE TABLE TB_RESUMO_FINANCEIRO (
   CD_USUARIO INT NOT NULL,
   MES INT NOT NULL,
   ANO INT NOT NULL,
   TOTAL_RECEITAS NUMERIC(10,2) NOT NULL,
   TOTAL_DESPESAS NUMERIC(10,2) NOT NULL,
   PRIMARY KEY(CD_USUARIO, MES, ANO)
)

CREATE OR ALTER PROCEDURE SP_OBTEM_RESUMO (@RECEITA_TOTAL NUMERIC(10,2) OUTPUT, @DESPESA_TOTAL NUMERIC(10,2) OUTPUT, @COD_FUNCIONARIO INT, @MES INT, @ANO INT) AS
BEGIN
	SET @RECEITA_TOTAL = (SELECT SUM(VALOR) FROM TB_LANCAMENTOS WHERE CD_USUARIO = @COD_FUNCIONARIO AND TP_LANCAMENTO = 'R' AND MES = @MES AND ANO = @ANO)
	SET @DESPESA_TOTAL = (SELECT SUM(VALOR) FROM TB_LANCAMENTOS WHERE CD_USUARIO = @COD_FUNCIONARIO AND TP_LANCAMENTO = 'D' AND MES = @MES AND ANO = @ANO)
END

CREATE OR ALTER PROCEDURE SP_INCLUI_RESUMO_FINANCEIRO (@ANO_RESUMO INT) AS
BEGIN
	DECLARE @CD_USUARIO INT, @NM_USUARIO INT, @MES_USUARIO INT, @TOTAL_R NUMERIC(10,2), @TOTAL_D NUMERIC(10,2)
	SET @MES_USUARIO = 1
	DECLARE C_TB_USUARIO CURSOR FOR SELECT CD_USUARIO, NM_USUARIO FROM TB_USUARIO
	OPEN C_TB_USUARIO
	FETCH C_TB_USUARIO INTO @CD_USUARIO, @NM_USUARIO
	WHILE(@@FETCH_STATUS = 0)
	BEGIN
		WHILE(@MES_USUARIO <= 12)
		BEGIN
			EXEC SP_OBTEM_RESUMO @TOTAL_R OUTPUT, @TOTAL_D OUTPUT, @CD_USUARIO, @MES_USUARIO, @ANO_RESUMO
			INSERT INTO TB_RESUMO_FINANCEIRO VALUES(@CD_USUARIO, @MES_USUARIO, @ANO_RESUMO, @TOTAL_R, @TOTAL_D)
			SET @MES_USUARIO = @MES_USUARIO + 1
		END
		FETCH C_TB_USUARIO INTO @CD_USUARIO, @NM_USUARIO
	END
	CLOSE C_TB_USUARIO
	DEALLOCATE C_TB_USUARIO
END

