CREATE DATABASE EX_08

USE EX_08

CREATE TABLE TB_CLIENTE (
  CD_CLIENTE INT NOT NULL PRIMARY KEY,
  NM_CLIENTE VARCHAR(60) NOT NULL,
  CPF INT nULl,
  DT_NASCIMENTO DATETIME,
  TIPO_CLIENTE VARCHAR(40) NULL
)


CREATE TABLE TB_CONTA (
   NR_CONTA INT NOT NULL PRIMARY KEY,
   CD_CLIENTE INT NOT NULL,
   SALDO NUMERIC(10,2) NOT NULL,
)

INSERT INTO TB_CLIENTE VALUES (1, 'MILENINHA', NULL, NULL, NULL),(2, 'MARIA', NULL, NULL, NULL),(3, 'ROLA', NULL, NULL, NULL),(4, 'HOSE', NULL, NULL, NULL),(5, 'MENINAN', NULL, NULL, NULL)
INSERT INTO TB_CONTA VALUES (1,1, 3000),(2,1, 7000),(3,2, 1000),(4,3, 8000),(5,4, 10000),(6,5, 20000),(7,5, 30000) 

CREATE OR ALTER PROCEDURE SP_CLASSIFICA_CLIENTE @QUANTIDADE_CONTAS INT, @SALDO_TOTAL NUMERIC(10,2), @TIPO_CONTA VARCHAR(10) OUTPUT AS
BEGIN
	IF @SALDO_TOTAL >= 10000 OR (@SALDO_TOTAL >= 5000 AND @QUANTIDADE_CONTAS > 2)
	BEGIN
		SET @TIPO_CONTA = 'VIP'
	END
	ELSE
	BEGIN
		SET @TIPO_CONTA = 'NORMAL'
	END
END

CREATE OR ALTER PROCEDURE SP_ATUALIZA_TIPO_CLENTE AS
BEGIN
	DECLARE @CODIGO INT
	DECLARE C_TB_CLIENTE CURSOR FOR SELECT CD_CLIENTE FROM TB_CLIENTE
	OPEN C_TB_CLIENTE
	FETCH C_TB_CLIENTE INTO @CODIGO

	DECLARE @QT_CONTAS INT, @SALDO_TT NUMERIC(10,2), @SAIDA_N VARCHAR(10)
	WHILE(@@FETCH_STATUS = 0)
	BEGIN
		SET @QT_CONTAS = (SELECT COUNT(NR_CONTA) FROM TB_CONTA WHERE CD_CLIENTE = @CODIGO)
		SET @SALDO_TT = (SELECT SUM(SALDO) FROM TB_CONTA WHERE CD_CLIENTE = @CODIGO)

		EXEC SP_CLASSIFICA_CLIENTE @QT_CONTAS, @SALDO_TT, @SAIDA_N OUTPUT

		UPDATE TB_CLIENTE
		SET TIPO_CLIENTE = @SAIDA_N
		WHERE CD_CLIENTE = @CODIGO

		FETCH C_TB_CLIENTE INTO @CODIGO
	END

	CLOSE C_TB_CLIENTE
	DEALLOCATE C_TB_CLIENTE
END

EXEC SP_ATUALIZA_TIPO_CLENTE

SELECT * FROM TB_CLIENTE

