CREATE DATABASE EX06

USE EX06

CREATE OR ALTER FUNCTION SF_TO_CHAR (@DATA DATETIME, @FORMATO VARCHAR(50))
RETURNS VARCHAR(50)
AS
BEGIN
	DECLARE @DATA_STRING VARCHAR(50)
	SET @DATA_STRING = REPLACE(@FORMATO,'DD',TRIM(STR(DAY(@DATA))))
	SET @DATA_STRING = REPLACE(@DATA_STRING,'MM',TRIM(STR(MONTH(@DATA))))
	SET @DATA_STRING = REPLACE(@DATA_STRING,'Month',TRIM(DATENAME(MM,@DATA)))
	SET @DATA_STRING = REPLACE(@DATA_STRING,'YYYY',TRIM(STR(YEAR(@DATA))))
	
	SET @DATA_STRING = REPLACE(@DATA_STRING,'HH',TRIM(STR(DATEPART(HH,@DATA))))
	SET @DATA_STRING = REPLACE(@DATA_STRING,'MI',TRIM(STR(DATEPART(MI,@DATA))))
	SET @DATA_STRING = REPLACE(@DATA_STRING,'SS',TRIM(STR(DATEPART(SS,@DATA))))

	RETURN @DATA_STRING
	
END

CREATE OR ALTER FUNCTION SF_TO_DATE (@DATA_VAR VARCHAR(50), @MASCARA VARCHAR(50)) 
RETURNS DATETIME
AS
BEGIN
	DECLARE @INDICE_DD INT, @INDICE_MM INT, @INDICE_YYYY INT, @STRING_DATA VARCHAR(50), @INDICE_HH INT, @INDICE_MI INT, @INDICE_SS INT
	SET @INDICE_DD = CHARINDEX('DD', @MASCARA)
	SET @INDICE_MM = CHARINDEX('MM', @MASCARA)
	SET @INDICE_YYYY = CHARINDEX('YYYY', @MASCARA)

	SET @INDICE_HH = CHARINDEX('HH', @MASCARA)
	SET @INDICE_MI = CHARINDEX('MI', @MASCARA)
	SET @INDICE_SS = CHARINDEX('SS', @MASCARA)

	SET @STRING_DATA = SUBSTRING(@DATA_VAR,@INDICE_YYYY,4)
	SET @STRING_DATA += SUBSTRING(@DATA_VAR,@INDICE_MM,2)
	SET @STRING_DATA += SUBSTRING(@DATA_VAR,@INDICE_DD,2)
	SET @STRING_DATA += ' '
	SET @STRING_DATA += SUBSTRING(@DATA_VAR,@INDICE_HH,2)
	SET @STRING_DATA += ':'
	SET @STRING_DATA += SUBSTRING(@DATA_VAR,@INDICE_MI,2)
	SET @STRING_DATA += ':'
	SET @STRING_DATA += SUBSTRING(@DATA_VAR,@INDICE_SS,2)

	--RETURN @INDICE_DD

	RETURN CAST(@STRING_DATA AS DATETIME)
END




PRINT dbo.sf_TO_CHAR (@DATA_sss, 'YYYYMMDD')

select dbo.sf_TO_CHAR(GETDATE(),'DD-MM-YYYY')
select dbo.sf_TO_CHAR(GETDATE(),'DD.MM.YYYY')

select dbo.sf_TO_CHAR(GETDATE(),'DD/MM/YYYY HH:MI:SS')
select dbo.sf_TO_CHAR(GETDATE(),'DD/MM/YYYY às HH:MI')

select dbo.sf_TO_CHAR(GETDATE(),'YYYYMMDD')
select dbo.sf_TO_CHAR(GETDATE(),'HH:MI')

SET LANGUAGE BRAZILIAN

select dbo.sf_TO_CHAR(GETDATE(),'DD de Month de YYYY')

select dbo.sf_TO_DATE('03/04/2011','DD/MM/YYYY')
select dbo.sf_TO_DATE('04-03-2011','DD-MM-YYYY')
select dbo.sf_TO_DATE('03.04.2011','DD.MM.YYYY')
select dbo.sf_TO_DATE('03/04/2011 21:25:34','DD/MM/YYYY HH:MI:SS')
select dbo.sf_TO_DATE('03/04/2011 às 21:27','DD/MM/YYYY às HH:MI')
select dbo.sf_TO_DATE('21:28','HH:MI')

SELECT CAST (' 20:30' AS DATETIME)