DROP TABLE TB_VALOR_BASE_PLANO
DROP TABLE TB_PLANO
DROP TABLE TB_DEPENDENTES
DROP TABLE TB_CLIENTE
DROP TABLE TB_ATENDIMENTOS

CREATE DATABASE AV_01_2019

USE AV_01_2019

DROP DATABASE AV_01_2019

-- Tabela Plano

CREATE TABLE TB_PLANO (
   COD_PLANO INT NOT NULL PRIMARY KEY,
   DESC_PLANO VARCHAR(100),
   FATOR_MODERADOR NUMERIC(10,2)
)

INSERT INTO TB_PLANO VALUES(10, 'BASICO', 70.00)
INSERT INTO TB_PLANO VALUES(20, 'PLUS', 20.00)


-- Tabela Valor Base Plano

CREATE TABLE TB_VALOR_BASE_PLANO (
   COD_BASE_PLANO INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
   COD_PLANO INT NOT NULL REFERENCES TB_PLANO (COD_PLANO),
   IDADE_MENOR INT NOT NULL,
   IDADE_MAIOR INT NOT NULL,
   VALOR NUMERIC(10,2) NOT NULL
)

INSERT INTO TB_VALOR_BASE_PLANO VALUES(10,0,17,'150.00')
INSERT INTO TB_VALOR_BASE_PLANO VALUES(10,18,40,'250.00')
INSERT INTO TB_VALOR_BASE_PLANO VALUES(10,41,110,'350.00')

INSERT INTO TB_VALOR_BASE_PLANO VALUES(20,0,17,'250.00')
INSERT INTO TB_VALOR_BASE_PLANO VALUES(20,18,40,'350.00')
INSERT INTO TB_VALOR_BASE_PLANO VALUES(20,41,110,'450.00')

-- Tabela Cliente

CREATE TABLE TB_CLIENTE (
   MATRICULA INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
   NOME VARCHAR(100) NOT NULL,
   CPF  VARCHAR(13) NOT NULL,
   DT_NASCIMENTO DATE NOT NULL,
   COD_PLANO INT NOT NULL REFERENCES TB_PLANO(COD_PLANO)
)

INSERT INTO TB_CLIENTE VALUES('JOAO SILVA','56626262626','19760120',10)
INSERT INTO TB_CLIENTE VALUES('ROBERTA SOUZA','78484884848','19500304',20)


-- Tabela Dependentes

CREATE TABLE TB_DEPENDENTES (
   MATRICULA_DEPENDENTE INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
   NOME VARCHAR(100) NOT NULL,
   CPF VARCHAR(13) NOT NULL,
   DT_NASCIMENTO DATE NOT NULL,
   MATRICULA INT NOT NULL
)

ALTER TABLE TB_DEPENDENTES ADD CONSTRAINT FK_TB_CLIENTE
FOREIGN KEY (MATRICULA) REFERENCES TB_CLIENTE (MATRICULA)

INSERT INTO TB_DEPENDENTES VALUES('PEDRO SILVA','77474747474','20090101',1)
INSERT INTO TB_DEPENDENTES VALUES('CARLA SILVA','66666666666','20150830',1)

INSERT INTO TB_DEPENDENTES VALUES('TIAGO SOUZA','33333333333','19800820',2)
INSERT INTO TB_DEPENDENTES VALUES('MARIO SOUZA','88888888888','20080820',2)


-- Tabela Atendimentos


CREATE TABLE TB_ATENDIMENTOS (
   COD_ATENDIMENTO INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
   DT_ATENDIMENTO DATETIME NOT NULL,
   CPF VARCHAR(13) NOT NULL
)

INSERT INTO TB_ATENDIMENTOS VALUES ('20190702', '56626262626')
INSERT INTO TB_ATENDIMENTOS VALUES ('20190703', '56626262626')

INSERT INTO TB_ATENDIMENTOS VALUES ('20190704', '33333333333')


--1

CREATE OR ALTER PROCEDURE SP_VALOR_PLANO (@CODIGO_PLANO INT, @DT_NASCIMENTO DATETIME, @DT_FATURA DATETIME, @VALOR_PLANO NUMERIC(10,2) OUTPUT)
AS
BEGIN
	DECLARE @IDADE INT
	SET @IDADE = DATEDIFF(yy,@DT_NASCIMENTO,@DT_FATURA)
	SET @VALOR_PLANO = (SELECT VALOR FROM TB_VALOR_BASE_PLANO WHERE COD_PLANO = @CODIGO_PLANO AND @IDADE >= IDADE_MENOR AND @IDADE <= IDADE_MAIOR)
END

DECLARE @VALOR NUMERIC(10,2)
EXEC SP_VALOR_PLANO 10, '19981009', '20220831', @VALOR OUTPUT

PRINT @VALOR

DECLARE @NUM NUMERIC(10,2)
EXEC SP_VALOR_PLANO 10, '20001030', '20190731', @NUM OUTPUT
PRINT @NUM

--2

CREATE OR ALTER PROCEDURE SP_POSSUI_ATENDIMENTO (@CPF_CLIENTE VARCHAR(13), @DT_FATURA DATETIME, @SAIDA INT OUTPUT) AS
BEGIN
	SET @SAIDA = 0
	IF EXISTS (SELECT CPF FROM TB_ATENDIMENTOS WHERE CPF = @CPF_CLIENTE AND MONTH(DT_ATENDIMENTO) = MONTH(@DT_FATURA))
	 BEGIN
		SET @SAIDA = 1
	 END
END

DECLARE @SAIDA_TESTE VARCHAR(20)

EXEC SP_POSSUI_ATENDIMENTO '33333333333', '20190704', @SAIDA_TESTE OUTPUT
PRINT @SAIDA_TESTE


-- 3 

CREATE OR ALTER PROCEDURE SP_GERAR_BOLETO (@DT_FATURA DATETIME) AS
BEGIN
	DECLARE C_CLIENTES CURSOR FOR SELECT MATRICULA, NOME, CPF, DT_NASCIMENTO, COD_PLANO FROM TB_CLIENTE
	DECLARE @MATRICULA INT,@NOME VARCHAR(100), @CPF VARCHAR(13), @DT_NASCIMENTO DATETIME, @COD_PLANO INT,
			@VALOR_PLANO NUMERIC(10,2), @VALOR_TOTAL NUMERIC(10,2), @DESC_PLANO VARCHAR(100)

	OPEN C_CLIENTES
	FETCH C_CLIENTES INTO @MATRICULA, @NOME, @CPF, @DT_NASCIMENTO, @COD_PLANO
	WHILE(@@FETCH_STATUS = 0)
	BEGIN
		SET @VALOR_TOTAL = 0
		PRINT REPLICATE('-',20)
		PRINT 'TITULAR:'+ @NOME
		PRINT 'CPF TITULAR:'+ @CPF
		SET @DESC_PLANO = (SELECT DESC_PLANO FROM TB_PLANO WHERE COD_PLANO = @COD_PLANO)
		PRINT 'PLANO:' + @DESC_PLANO
		PRINT REPLICATE('-',20)
		PRINT 'Nome' + REPLICATE(' ',7) + 'Valor'

		EXEC SP_VALOR_PLANO @COD_PLANO,@DT_NASCIMENTO, @DT_FATURA ,@VALOR_PLANO OUTPUT
		PRINT @NOME + REPLICATE(' ',7) + STR(@VALOR_PLANO)
		SET @VALOR_TOTAL += @VALOR_PLANO

		IF EXISTS (SELECT * FROM TB_DEPENDENTES WHERE MATRICULA = @MATRICULA)
		BEGIN
			DECLARE C_DEPENDENTES CURSOR FOR SELECT NOME, CPF, DT_NASCIMENTO FROM TB_DEPENDENTES WHERE MATRICULA = @MATRICULA
			DECLARE @NOME_DEPENDENTE VARCHAR(100), @CPF_DEPENDENTE VARCHAR(13), @DT_NASCIMENTO_DEP DATETIME

			OPEN C_DEPENDENTES
			FETCH C_DEPENDENTES INTO @NOME_DEPENDENTE, @CPF_DEPENDENTE, @DT_NASCIMENTO_DEP
			WHILE(@@FETCH_STATUS = 0)
			BEGIN
				DECLARE @FLAG_ATED INT
				EXEC SP_POSSUI_ATENDIMENTO @CPF_DEPENDENTE, @DT_FATURA, @FLAG_ATED OUTPUT
				IF @FLAG_ATED = 1
				BEGIN
					EXEC SP_VALOR_PLANO @COD_PLANO,@DT_NASCIMENTO_DEP, @DT_FATURA ,@VALOR_PLANO OUTPUT
					PRINT @NOME_DEPENDENTE + REPLICATE(' ',7) + STR(@VALOR_PLANO)
					SET @VALOR_TOTAL += @VALOR_PLANO
				END

				FETCH C_DEPENDENTES INTO @NOME_DEPENDENTE, @CPF_DEPENDENTE, @DT_NASCIMENTO_DEP
			END
			CLOSE C_DEPENDENTES
			DEALLOCATE C_DEPENDENTES
		END
		PRINT 'Total Boleto:' + STR(@VALOR_TOTAL)
		FETCH C_CLIENTES INTO @MATRICULA, @NOME, @CPF, @DT_NASCIMENTO, @COD_PLANO
	END
	CLOSE C_CLIENTES
	DEALLOCATE C_CLIENTES
END
-- Teste


exec sp_gerar_boleto '20190731'
SELECT * FROM TB_ATENDIMENTOS


------------------------------
TITULAR:JOAO SILVA
CPF TITULAR:56626262626
PLANO:BASICO
------------------------------
Nome                Valor
JOAO SILVA          420.00
PEDRO SILVA         150.00
CARLA SILVA         150.00
 
Total Fatura:       720.00
 
------------------------------
TITULAR:ROBERTA SOUZA
CPF TITULAR:78484884848
PLANO:PLUS
------------------------------
Nome                Valor
ROBERTA SOUZA       450.00
TIAGO SOUZA         370.00
 
Total Fatura:       820.00