CREATE TABLE TB_CATEGORIA (
    CD_CATEGORIA NUMBER PRIMARY KEY NOT NULL,
    NM_CATEGORIA VARCHAR2(50) NOT NULL
)

INSERT INTO TB_CATEGORIA VALUES(1,'FICÇÃO');
INSERT INTO TB_CATEGORIA VALUES(2,'ROMANCE');
INSERT INTO TB_CATEGORIA VALUES(3,'TERROR');

CREATE TABLE TB_LIVRO (
    CD_LIVRO NUMBER NOT NULL,
    TITULO VARCHAR2(50) NOT NULL,
    PRECO NUMBER(10,2) NOT NULL,
    CD_CATEGORIA NUMBER NOT NULL
)

INSERT INTO TB_LIVRO VALUES(1,'Nárnia - A bruxa e o Imposto de Renda',20.00,1);
INSERT INTO TB_LIVRO VALUES(2,'50 Tons de Cinza',00.00,2);
INSERT INTO TB_LIVRO VALUES(3,'Cthulhu',30.00,3);
INSERT INTO TB_LIVRO VALUES(4,'Os Trapalhões',30.00,3);
INSERT INTO TB_LIVRO VALUES(5,'Rico em 6 meses',10.00,1);

DELETE TB_LIVRO WHERE TITULO = 'Rico em 6 meses';

CREATE TABLE TB_ESTATISTICA (
    NM_CATEGORIA VARCHAR2(50) NOT NULL,
    TOTAL_LIVROS NUMBER NOT NULL,
    PRECO_MEDIO NUMBER(10,2) NOT NULL
)

CREATE OR REPLACE TRIGGER
    TG_INSERT_UPDATE_TB_LIVRO
AFTER INSERT OR UPDATE OR DELETE ON TB_LIVRO
BEGIN
    DELETE tb_estatistica;

    FOR R_LIV IN (SELECT C.NM_CATEGORIA AS NOME, COUNT(L.CD_LIVRO) AS TOTAL, AVG(L.PRECO) AS PRECO FROM tb_categoria C 
                  INNER JOIN TB_LIVRO L ON C.CD_CATEGORIA = L.CD_CATEGORIA
                  GROUP BY C.NM_CATEGORIA) LOOP
                  
                INSERT INTO tb_estatistica VALUES (R_LIV.NOME, R_LIV.TOTAL, R_LIV.PRECO);
    END LOOP;
END;

SELECT * FROM TB_ESTATISTICA;