DROP TABLE TB_ESTOQUE;
DROP TABLE TB_AUDITORIA_ESTOQUE;

CREATE TABLE TB_ESTOQUE (
    CODIGO NUMBER(3) PRIMARY KEY,
    DESCRICAO VARCHAR2(100) NOT NULL, 
    PRECO_UNITARIO NUMBER(10,2) NOT NULL,
    QUANTIDADE NUMBER(3) NOT NULL,
    STATUS CHAR(1) CHECK(STATUS IN ('A', 'I'))
);

CREATE SEQUENCE SQ_ESTOQUE 
    START WITH 1
    INCREMENT BY 1;
    
INSERT INTO tb_estoque (CODIGO, DESCRICAO, PRECO_UNITARIO, QUANTIDADE, STATUS)
    VALUES (SQ_ESTOQUE.NEXTVAL, 'LEITE EM PÓ 4KG', 5.50, 10, 'A');
    
INSERT INTO tb_estoque (CODIGO, DESCRICAO, PRECO_UNITARIO, QUANTIDADE, STATUS)
    VALUES (SQ_ESTOQUE.NEXTVAL, 'FANTA UVA 2L', 3.00, 5, 'A');

CREATE TABLE TB_AUDITORIA_ESTOQUE (
    USUARIO VARCHAR2(30) NOT NULL,
    DATA DATE NOT NULL,
    MUDANCA CHAR(1) NOT NULL,
    CODIGO_ANTIGO NUMBER(4) NULL,
    CODIGO_NOVO NUMBER(4) NULL,
    DESCRICAO_ANTIGA VARCHAR(40) NULL,
    DESCRICAO_NOVA VARCHAR(40) NULL,
    PRECO_ANTIGO NUMBER(10,2) NULL,
    PRECO_NOVO NUMBER(10,2) NULL,
    QUANTIDADE_ANTIGA NUMBER(4) NULL,
    QUANTIDADE_NOVA NUMBER(4) NULL,
    STATUS_ANTIGO CHAR(1) NULL,
    STATUS_NOVO CHAR(1) NULL
);

CREATE OR REPLACE TRIGGER TG_INSERT_IN_TB_AUDITORIA
BEFORE INSERT OR UPDATE OR DELETE ON TB_ESTOQUE
FOR EACH ROW 
DECLARE 
    OPERACAO CHAR(1);
BEGIN
    IF INSERTING THEN
        OPERACAO := 'I';
    END IF;
    
    IF UPDATING THEN
        OPERACAO := 'A';
    END IF;
    
    IF DELETING THEN 
        OPERACAO := 'R';
    END IF;
    
    
    INSERT INTO TB_AUDITORIA_ESTOQUE (USUARIO, DATA, MUDANCA, CODIGO_ANTIGO, CODIGO_NOVO, 
                                      DESCRICAO_ANTIGA, DESCRICAO_NOVA, PRECO_ANTIGO, PRECO_NOVO, 
                                      QUANTIDADE_ANTIGA, QUANTIDADE_NOVA, STATUS_ANTIGO, STATUS_NOVO)
    VALUES (USER, SYSDATE, OPERACAO, :OLD.CODIGO, :NEW.CODIGO,
            :OLD.DESCRICAO, :NEW.DESCRICAO, :OLD.PRECO_UNITARIO, :NEW.PRECO_UNITARIO, 
            :OLD.QUANTIDADE, :NEW.QUANTIDADE, :OLD.STATUS, :NEW.STATUS);

END;

-- TESTE
INSERT INTO tb_estoque (CODIGO, DESCRICAO, PRECO_UNITARIO, QUANTIDADE, STATUS)
    VALUES (SQ_ESTOQUE.NEXTVAL, 'CUZ CUZ 500g', 1.25, 5, 'A');

SELECT * FROM tb_auditoria_estoque;

UPDATE tb_estoque
SET quantidade = 20
WHERE codigo = 3;

SELECT * FROM tb_auditoria_estoque;

DELETE FROM tb_estoque WHERE codigo = 3;

SELECT * FROM tb_auditoria_estoque;