DROP DATABASE EX05_TR
CREATE DATABASE EX05_TR

USE EX05_TR

DROP TABLE TB_LOG_VENDAS
DROP TABLE TB_VENDAS

CREATE TABLE TB_VENDAS (
   CD_VENDA INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
   DT_VENDA DATETIME NOT NULL,
   CD_PRODUTO INT NOT NULL,
   QUANTIDADE INT NOT NULL,
   VALOR NUMERIC(10,2) NOT NULL
)


/* Tabela para log de altera��es na tabela de Vendas. As altera��es podem
   ser de tr�s tipos: (I - Inclusao, A - Alteracao, R - Remocao). O Log
   sempre armazena os valores antigos e os novos valores. Somente os 
   os atributos QUANTIDADE e VALOR podem ser alterados para uma venda. */

CREATE TABLE TB_LOG_VENDAS (
    CD_LOG 		INT IDENTITY (1,1) NOT NULL,
    DT_LOG 		DATETIME NOT NULL,     -- Data em que o log foi registrado
    TIPO_OPERACAO 	CHAR(1) CHECK (TIPO_OPERACAO IN ('I','A','R')),	
    CD_VENDA 		INT NULL,
    CD_PRODUTO 		INT NULL,
    DT_VENDA 		DATETIME NULL,
    QUANTIDADE_ANTIGA   INT NULL,
    VALOR_ANTIGO	NUMERIC(10,2) NULL,
    QUANTIDADE_NOVA	INT NULL,
    VALOR_NOVO		NUMERIC(10,2) NULL 
)

CREATE OR ALTER TRIGGER T_I_U_LOG_VENDAS ON TB_VENDAS 
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
	-- UPDATE
	IF EXISTS (SELECT 1 FROM INSERTED) AND EXISTS (SELECT 1 FROM DELETED)
	BEGIN
		
		INSERT INTO TB_LOG_VENDAS
		SELECT GETDATE(), 'A', CD_VENDA, CD_PRODUTO, DT_VENDA,
		(SELECT QUANTIDADE FROM DELETED WHERE CD_VENDA = I.CD_VENDA), 
		(SELECT VALOR FROM DELETED WHERE CD_VENDA = I.CD_VENDA) 
		,QUANTIDADE, VALOR FROM INSERTED I

		RETURN
	END
	-- INSERT
	ELSE IF EXISTS (SELECT 1 FROM INSERTED)
	BEGIN
		INSERT INTO TB_LOG_VENDAS (DT_LOG, TIPO_OPERACAO, CD_VENDA, CD_PRODUTO, DT_VENDA, QUANTIDADE_NOVA, VALOR_NOVO)
		SELECT GETDATE(), 'I', CD_VENDA, CD_PRODUTO, DT_VENDA, QUANTIDADE, VALOR FROM INSERTED

		RETURN
	END
	-- DELETE
	ELSE
	BEGIN
		INSERT INTO TB_LOG_VENDAS (DT_LOG, TIPO_OPERACAO, CD_VENDA, CD_PRODUTO, DT_VENDA)
		SELECT GETDATE(), 'R', CD_VENDA, CD_PRODUTO, DT_VENDA FROM DELETED
	END
END

-- TESTES
DELETE TB_VENDAS
DELETE TB_LOG_VENDAS
-- INSERT
INSERT INTO TB_VENDAS VALUES(GETDATE(),1,2,30),
							(GETDATE(),1,4,60),
							(GETDATE(),1,6,90)

SELECT * FROM TB_LOG_VENDAS

-- UPDATE
UPDATE TB_VENDAS SET VALOR = 120, QUANTIDADE = 8 WHERE CD_VENDA IN (1,3)

SELECT * FROM TB_LOG_VENDAS

-- DELETE
DELETE TB_VENDAS WHERE CD_VENDA IN (1,3)

SELECT * FROM TB_LOG_VENDAS