DROP TABLE TB_ALUNO
DROP TABLE TB_LOG_PENDENCIAS

CREATE TABLE TB_ALUNO (
    MATRICULA INT NOT NULL PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL,
    RG INT NULL,
    ENDERECO VARCHAR(100) NULL,
    TELEFONE VARCHAR (20) NULL,
)

CREATE TABLE TB_LOG_PENDENCIAS (
  MATRICULA INT,
  NOME VARCHAR(50),
  PENDENCIA VARCHAR(200)
)

CREATE OR ALTER TRIGGER TB_INSERT_ALUNO ON TB_ALUNO
AFTER INSERT,UPDATE AS
BEGIN
	DECLARE @MATRICULA INT, @NOME VARCHAR(50), @RG INT, @ENDERECO VARCHAR(100), @TELEFONE VARCHAR(20)
	DECLARE C_INSERTED CURSOR FOR SELECT MATRICULA, NOME, RG, ENDERECO, TELEFONE FROM INSERTED

	OPEN C_INSERTED
	FETCH C_INSERTED INTO @MATRICULA, @NOME, @RG, @ENDERECO, @TELEFONE
	WHILE(@@FETCH_STATUS = 0)
	BEGIN
		DELETE FROM TB_LOG_PENDENCIAS WHERE MATRICULA = @MATRICULA
		IF @RG IS NULL
		BEGIN
			INSERT INTO TB_LOG_PENDENCIAS VALUES(@MATRICULA, @NOME, 'FALTOU RG')
		END
		IF @ENDERECO IS NULL
		BEGIN
			INSERT INTO TB_LOG_PENDENCIAS VALUES(@MATRICULA, @NOME, 'FALTOU ENDERECO')
		END
		IF @TELEFONE IS NULL
		BEGIN
			INSERT INTO TB_LOG_PENDENCIAS VALUES(@MATRICULA, @NOME, 'FALTOU TELEFONE')
		END
		FETCH C_INSERTED INTO @MATRICULA, @NOME, @RG, @ENDERECO, @TELEFONE
	END
	CLOSE C_INSERTED
	DEALLOCATE C_INSERTED
END

DROP TRIGGER TB_INSERT_ALUNO

CREATE OR ALTER TRIGGER TB_INSERT_ALUNO_SEM_C ON TB_ALUNO
AFTER INSERT,UPDATE AS
BEGIN
	DELETE TB_LOG_PENDENCIAS WHERE MATRICULA IN (SELECT MATRICULA FROM INSERTED)

	INSERT INTO TB_LOG_PENDENCIAS SELECT MATRICULA, NOME, 'FALTOU RG' FROM INSERTED WHERE RG IS NULL
	INSERT INTO TB_LOG_PENDENCIAS SELECT MATRICULA, NOME, 'FALTOU ENDERECO' FROM INSERTED WHERE ENDERECO IS NULL
	INSERT INTO TB_LOG_PENDENCIAS SELECT MATRICULA, NOME, 'FALTOU TELEFONE' FROM INSERTED WHERE TELEFONE IS NULL
END

INSERT INTO TB_ALUNO VALUES(1,'João',232324,NULL,NULL)
					 ,(2,'Pedro',NULL,NULL,NULL)
DELETE TB_ALUNO

SELECT TOP 2 * FROM TB_ALUNO

SELECT * FROM TB_ALUNO
SELECT * FROM TB_LOG_PENDENCIAS

DELETE TB_LOG_PENDENCIAS

UPDATE TB_ALUNO SET TELEFONE = NULL, RG = NULL WHERE MATRICULA = 2 

UPDATE TB_ALUNO SET TELEFONE = '22', RG = 223 WHERE MATRICULA = 2 


CREATE OR ALTER TRIGGER TB_DELETE_ALUNO ON TB_ALUNO
AFTER DELETE AS
BEGIN
	DELETE TB_LOG_PENDENCIAS WHERE MATRICULA IN (SELECT MATRICULA FROM DELETED)
END
