DROP DATABASE EX04_TR
CREATE DATABASE EX04_TR

USE EX04_TR

CREATE TABLE TB_FUNCIONARIO(
	MATRICULA INT NOT NULL PRIMARY KEY, 
	NOME VARCHAR(70) NOT NULL, 
	DEPARTAMENTO VARCHAR(70) NOT NULL, 
	SALARIO NUMERIC(10,2) NULL, 
	GRATIFICACAO NUMERIC(10,2) NULL
	)

CREATE OR ALTER TRIGGER T_VERIFICA_SALARIO ON TB_FUNCIONARIO
AFTER UPDATE AS
BEGIN
	IF EXISTS (SELECT MATRICULA FROM INSERTED I
			  WHERE (ISNULL(I.SALARIO,0) + ISNULL(I.GRATIFICACAO,0) - (SELECT ISNULL(D.SALARIO,0) + ISNULL(D.GRATIFICACAO,0) FROM DELETED D WHERE D.MATRICULA = I.MATRICULA)) > 
			  (SELECT ISNULL(D.SALARIO,0) + ISNULL(D.GRATIFICACAO,0) FROM DELETED D WHERE D.MATRICULA = I.MATRICULA)*0.3)
	BEGIN
		RAISERROR ('INVALIDO',1,1)
		ROLLBACK
		RETURN
	END
END
DELETE TB_FUNCIONARIO
INSERT INTO TB_FUNCIONARIO VALUES(1,'Lauro','DSI',100,NULL),
								 (2,'Joana','DSI',100,NULL),
								 (3,'Sergio','DSI',100,NULL)

UPDATE TB_FUNCIONARIO SET SALARIO = 200