DROP DATABASE EX07_TR
CREATE DATABASE EX07_TR

USE EX07_TR

CREATE TABLE TB_FUNCIONARIO (
  MATRICULA INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
  NOME  VARCHAR(100) NOT NULL,
  CARGO VARCHAR(100) NOT NULL,
  SALARIO NUMERIC (10,2)
) 

/* Tabela para log de altera��es na tabela de Funcionario. As altera��es podem
   ser de tr�s tipos: (I - Inclusao, A - Alteracao, R - Remocao).  */


CREATE TABLE TB_LOG_FUNCIONARIO
(
    CD_LOG 		INT IDENTITY (1,1) NOT NULL,
    DT_LOG 		DATETIME NOT NULL,     -- Data em que o log foi registrado
    TIPO_OPERACAO 	CHAR(1) CHECK (TIPO_OPERACAO IN ('I','A','R')),	
    MATRICULA 		INT NOT NULL,
    NOME  		VARCHAR(100) NOT NULL,
    MODIFICACAO		VARCHAR(500) NOT NULL
)

CREATE OR ALTER TRIGGER T_I_U_LOG_FUNCIONARIO ON TB_FUNCIONARIO
AFTER UPDATE, INSERT
AS
BEGIN
	-- UPDATE
	IF EXISTS (SELECT 1 FROM DELETED)
	BEGIN

		INSERT INTO TB_LOG_FUNCIONARIO
		SELECT GETDATE(),'A', MATRICULA, NOME, 
		IIF(I.SALARIO > (SELECT SALARIO FROM DELETED WHERE MATRICULA = I.MATRICULA),
		'Aumento de Salario',
		'Reducao de Salario') 
		FROM INSERTED I

		INSERT INTO TB_LOG_FUNCIONARIO
		SELECT GETDATE(),'A', MATRICULA, NOME, 'Alteracao de Cargo' FROM INSERTED
		WHERE CARGO NOT IN (SELECT CARGO FROM DELETED)

	END
	-- INSERT
	ELSE
	BEGIN
		INSERT INTO TB_LOG_FUNCIONARIO
		SELECT GETDATE(), 'I', MATRICULA, NOME, 'Inclusao de novo funcionario' FROM INSERTED
	END
END

CREATE OR ALTER TRIGGER T_D_LOG_FUNCIONARIO ON TB_FUNCIONARIO
AFTER DELETE
AS
BEGIN
	INSERT INTO TB_LOG_FUNCIONARIO 
	SELECT GETDATE(), 'R', MATRICULA, NOME, 'Remocao de funcionario' FROM DELETED
END
DELETE TB_FUNCIONARIO
DELETE TB_LOG_FUNCIONARIO

INSERT TB_FUNCIONARIO VALUES('Lauro','DBA',3000),
							('Laura','Chefe',2000),
							('Daniel','Atendente',200)
SELECT * FROM TB_LOG_FUNCIONARIO

UPDATE TB_FUNCIONARIO SET SALARIO = 2500
SELECT * FROM TB_LOG_FUNCIONARIO

DELETE TB_FUNCIONARIO WHERE MATRICULA IN (10,12)
SELECT * FROM TB_LOG_FUNCIONARIO