CREATE DATABASE TRIG_03

USE TRIG_03

CREATE TABLE TB_FUNCIONARIO(
	MATRICULA INT NOT NULL PRIMARY KEY,
	NOME VARCHAR(70) NOT NULL,
	SALARIO NUMERIC(10,2) NULL,
	GRATIFICACAO NUMERIC(10,2) NULL
)

INSERT INTO TB_FUNCIONARIO VALUES (1,'Joao',2000,100), (2,'Pedro',3000,50), (3,'Sergio',1000,500)

CREATE TABLE TB_LOG_AUMENTO_FUNCIONARIO(
	ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	MATRICULA INT NOT NULL,
	NOME VARCHAR(70) NOT NULL,
	DATA DATETIME NOT NULL,
	SALARIO_INTEGRAL_ANTIGO NUMERIC(10,2) NULL,
	SALARIO_INTEGRAL_NOVO NUMERIC(10,2) NULL
)

CREATE OR ALTER TRIGGER TR_FUNCIONARIO ON TB_FUNCIONARIO AFTER UPDATE
AS 
BEGIN
	INSERT INTO TB_LOG_AUMENTO_FUNCIONARIO SELECT MATRICULA, NOME, GETDATE() ,
				(SELECT SALARIO + GRATIFICACAO FROM DELETED WHERE MATRICULA = I.MATRICULA), 
				(SELECT SALARIO + GRATIFICACAO FROM INSERTED WHERE MATRICULA = I.MATRICULA)
				FROM INSERTED I
				WHERE (SELECT SALARIO + GRATIFICACAO FROM INSERTED WHERE MATRICULA = I.MATRICULA) > (SELECT SALARIO + GRATIFICACAO FROM DELETED WHERE MATRICULA = I.MATRICULA)
END

DELETE TB_FUNCIONARIO
DELETE TB_LOG_AUMENTO_FUNCIONARIO

INSERT INTO TB_FUNCIONARIO VALUES (1,'Joao',2000,100), (2,'Pedro',3000,50), (3,'Sergio',1000,500)

UPDATE TB_FUNCIONARIO SET SALARIO = 2000

SELECT * FROM TB_LOG_AUMENTO_FUNCIONARIO