DROP DATABASE EX07_TR
CREATE DATABASE EX08_TR

USE EX08_TR

CREATE TABLE TB_VENDAS (
   CD_VENDA INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
   DT_VENDA DATETIME NOT NULL,
   CD_PRODUTO INT NOT NULL,
   QUANTIDADE INT NOT NULL,
   VALOR NUMERIC(10,2) NOT NULL
)

CREATE OR ALTER TRIGGER T_VALIDA_INSERT ON TB_VENDAS
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
	DECLARE @HORA INT
	SET @HORA = DATEPART(hh,GETDATE())
	IF (@HORA >= 12 AND @HORA < 14) OR (@HORA >= 18 AND @HORA < 22)
	BEGIN
		RAISERROR('TABELA INDISPONIVEL',1,1)
		ROLLBACK
	END
END

INSERT INTO TB_VENDAS VALUES (GETDATE(), 1, 2, 30)