CREATE DATABASE DB_TRIG_10

USE DB_TRIG_10

CREATE TABLE TB_PADROES(
	ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	TIPO VARCHAR(20) NOT NULL,
	PREFIXO VARCHAR(20) NOT NULL
)

INSERT INTO TB_PADROES VALUES
					   ('TABLE','TB_'),
					   ('PROCEDURE','SP_'),
					   ('VIEW','VW_'),
					   ('FUNCTION','FU_')

CREATE OR ALTER TRIGGER TR_CONTEXT 
ON DATABASE
FOR CREATE_TABLE, CREATE_VIEW, CREATE_PROCEDURE, CREATE_FUNCTION
AS
BEGIN
	DECLARE @EVENTO_XML XML, @NOME NVARCHAR(100), @TIPO NVARCHAR(50)
	SET @EVENTO_XML = EVENTDATA()
	SET @NOME = @EVENTO_XML.value('(/EVENT_INSTANCE/ObjectName)[1]','nvarchar(100)')
	SET @TIPO = @EVENTO_XML.value('(/EVENT_INSTANCE/ObjectType)[1]','nvarchar(50)')
	--SELECT @EVENTO_XML
	--SELECT LEFT(@NOME,3)
	IF LEFT(@NOME,3) NOT IN (SELECT PREFIXO FROM TB_PADROES WHERE TIPO = @TIPO)
	BEGIN
		RAISERROR('OBJETO COM NOME INVALIDO',1,1)
		ROLLBACK
	END
END


CREATE TABLE TABELA(
	TTT INT NOT NULL)

DROP TABLE TABELA

CREATE PROCEDURE PROCEDURI AS

DROP PROCEDURE PROCEDURI

CREATE TABLE SP_TABELA(
	TT INT NOT NULL)

CREATE VIEW VW_VIEEW AS SELECT * FROM TB_PADROES

DROP VIEW VW_VIEEW

CREATE FUNCTION TB_FUNCTION ()
RETURNS VARCHAR(20) AS
BEGIN
	RETURN 'TTT'
END


